### ISSUE TITLE
chore: add specification of which AMMs need to be at least considered in solution (EBBO)

### ISSUE THREAD

**Issue by fleupold** [cowprotocol/docs#136]
https://github.com/cowprotocol/docs-v2/blob/ae8e1316e4db5ff899871d76dbb3824be82f506b/docs/cow-protocol/reference/core/auctions/social_consensus.md?plain=1#L20

Probably not having some random AMM on some exotic token qualifies here, instead we should define a list of protocols and base token pairs that need to be considered?

**Comment by mfw78** [comment]
@harisang Can we close this with #148 having been merged ?

**Comment by harisang** [comment]
I deliberately kept this open as Felix seems to suggest we might need to specify "base token pairs" that need to be considered.

For now, PR #148 added this sentence

> This rule is often referenced as "EBBO" (Ethereum Best Bid and Offer), and the AMMs that "should" be considered by solvers when computing an execution route for an order are referenced as "Baseline liquidity", and contain Uniswap v2/v3, Sushiswap, and Balancer pools.

But I admit this might be too generic and one has to understand what kind of pools the driver fetches and sends to solvers that ask for driver liquidity, because this is what we usually refer to as baseline liquidity. Maybe @fleupold or @sunce86 can briefly mention here how we decide which pools to fetch in each batch auction instance?

**Comment by fleupold** [comment]
The backend is configured with a set of base tokens and tries to index all AMMs with sell_token<>base_token buy_token<>base_token and sell_token<>buy_token if they exist.
