### ISSUE TITLE
chore: simplify auction jargon in cancellation partial

### ISSUE THREAD

**Issue by MindyCoW** [cowprotocol/docs#169]
As mentioned in [this issue](https://github.com/cowprotocol/docs-v2/issues/168), the use of "intent" to refer to a pending order is likely confusing for a user who needs tutorials. 

This snippet also refers to "auctions," which a tutorial reader also doesn't need to know about. 

Recommend either:
- Changing instances of "intent" in this snippet to "order" and removing references to auctions, or
- Decoupling this snippet from the Cancel tutorial and re-writing the same content there in simpler language

https://github.com/cowprotocol/docs-v2/blob/a430ab26b52a2f157cf08b8fbcc0b8e190be512d/docs/partials/_cancellation_offchain_versus_onchain.mdx#L5-L6

**Comment by mfw78** [comment]
Would a link from auction to the concepts section "Batch Auctions" alleviate the concern here?

**Comment by MindyCoW** [comment]
Theoretically, but isn't the point of the Tutorial section to provide quick, practical info without bogging the user down in concepts?

**Comment by mfw78** [comment]
Sure, it is quick and practical, however this doesn't preclude having links to other information _available_. A user doesn't have to understand the batch auction in order to cancel, but they _do_ need to know that cancellation is not immediate (in-flight orders may be settled) and depends on some _other factor_ (in this case, the cadence of batch auctions).

**Comment by MindyCoW** [comment]
Sure, but it's much simpler to just say, "Cancellations are not immediate, and your order may settle before the cancellation goes through" rather than use terminology the user isn't familiar with. 

What is your concern about decoupling the snippet here? Is there a possibility that our cancellation mechanism might change in the future and this page would need to be updated?

**Comment by mfw78** [comment]
From potential architectural changes, there doesn't seem to be much of a way in which the cancellation methodology will change. It's more that if we write tutorials, from a learning perspective, I find it great to still provide hyperlinks to other information so that the user may have self-directed learning, if that's something that they wish to undertake.

In the meantime, thanks for the recommended change in language, I'll use this an PR it.
