### ISSUE TITLE
Does this belong in the Concepts section?

### ISSUE THREAD

**Issue by marshymarsh** [cowprotocol/docs#193]
https://github.com/cowprotocol/docs-v2/blob/e851b2b831fdea12a90b3d0a47aaea71f98e53ad/docs/cow-protocol/reference/core/auctions/README.mdx#L1

**Comment by mfw78** [comment]
Are you referring to this section, or this specific part of the section (ie. just the cited file?).

In the former case: No, as this section contains concrete implementation details for the batch auction mechanism.

In the latter case: The documentation is designed such that the reference is solely that - reference. Otherwise if this section were moved to Concepts, there would be no intro-like material here, and it would require hyperlinking to Concepts. Reference material should avoid any hyperlinks to concepts or tutorials.
