### ISSUE TITLE
bug: Solvers tutorials are not accessible

### ISSUE THREAD

**Issue by harisang** [cowprotocol/docs#285]
I just realized that the solvers tutorials are not accessible/linked from anywhere, although the source files are there.

**Comment by mfw78** [comment]
The source files are there, however as they are in `draft: true` within the front-matter, they aren't shown in the production version of the documentation. In order to move them out of draft, remove the `draft: true` from the docs and it will make it visible.

It also follows that #286 is irrelevant :+1:

**Comment by harisang** [comment]
Wasn't aware of this, thanks! So closing this as it is a non-issue after all.
