### ISSUE TITLE
chore: improve MEV Protection section

### ISSUE THREAD

**Issue by fleupold** [cowprotocol/docs#96]
https://github.com/cowprotocol/docs-v2/blob/bf73c4804e225abcd2443c0806b40d2228b9bd01/docs/cow-protocol/concepts/batch-auctions/mev-protection.md?plain=1#L7

This part is mentioning in one sentence how we protect from MEV in the absence and presence of CoWs. I think we should have sections that explain both of the two protection in detail (with example transactions for both).

- One transaction where the user set a large slippage but the solver set a tight slippage
- One transaction where the solver got sandwiched (but the user got a better price)
- One perfect CoW and how transaction ordering is irrelevant (no MEV)

We can potentially also reuse the high level diagram we presented in https://docs.google.com/presentation/d/1AB2Eok6nOuUOAMPqIrgSFhZIg39Tw9jHohMg7H5kF0E/edit#slide=id.ge38a0b1903_0_134

**Comment by mfw78** [comment]
This has been improved by @acanidio-econ, and the [PR](https://github.com/cowprotocol/docs-v2/pull/91) was building. Will assign @acanidio-econ for review.

**Comment by acanidio-econ** [comment]
I don't think we need to explain further that if there is a perfect COW then there is no MEV (we can, of course, provide an example of a perfect COW, but not so much to illustrate the absence of MEV but to illustrate the possibility of a perfect COW). Also, the example of a loose slippage tolerance from a user and tight slippage tolerance from a solver would be a bit misleading because the user set the loose slippage tolerance knowing that a solver will then set its own slippage tolerance, so I'm not too sure what would be the takeaway. 

But I think we can expand a bit on the various ways in which solvers avoid MEV: setting appropriate slippage tolerance, using private RPC endpoint like Mev Blocker, working directly with private market makers, ... And a concrete example in which a solver was sandwiched but had to provide the amount initially promised anyway would indeed be useful.

**Comment by fleupold** [comment]
> because the user set the loose slippage tolerance knowing that a solver will then set its own slippage tolerance, so I'm not too sure what would be the takeaway.

Imo the take-away is that it's safe to set loose slippage tolerances as the slippage tolerance the user sets has nothing to do with the slippage tolerance a malicious sandwich bot would have access to.
